Assets/Scenes/SampleScene.unity, Assets/Scripts/RotationController.cs
Patched controller to have bounded movement.
=> Rotation controller patch

Assets/Materials/DiagDefault-Blue.mat, Assets/Materials/DiagDefault-Blue.mat.meta, Assets/Materials/SquareDefault-Blue.mat, Assets/Materials/SquareDefault-Blue.mat.meta, Assets/Prefabs.meta, Assets/Prefabs/Environment.meta, Assets/Prefabs/Environment/TestSurface.prefab, Assets/Prefabs/Environment/TestSurface.prefab.meta, Assets/Scenes/SampleScene.unity, Assets/Scripts/Pusher.cs, Assets/Scripts/Pusher.cs.meta, Assets/Textures/DiagDefault-Blue.png, Assets/Textures/DiagDefault-Blue.png.meta, Assets/Textures/SquareDefault-Blue.png, Assets/Textures/SquareDefault-Blue.png.meta, SampleImages/Demo/push.gif
Pushing Cubes (Player controller can now push objects, yay)
Fixed bug where cubes go through floor but don't feel like making a new example gif.
=> Pushing cubes

pull_request_template.md
Making the formatting consistent so the last two bullet points on checklist don't look differently formatted than the others. Also starting with the last two checked as they cannot be completed yet and just to ignore them until we have a testing framework setup.
No affect on the codebase
=> Adjustment to PR template

Authors.csv
=> Adding name to authors.

Assets/Scripts/Mixed/Systems/KinematicCharacterControllerSystems.cs
Added some basic optimization for the Kinematic character controller for basic state changes including jumping, grounded, and gravity systems. 
This has been tested by executing the game in client server mode and producing the same results as before when the jobs were simply ComponentSystems. It seems to follow the normal use cases and woks just fine. 
Closes #42 (at least somewhat, does not handle the more complex task of projection movement)
=> Basic KCC Optimization

Assets/Scripts/Authoring/PlayerMovementAuthoringComponent.cs, Assets/Scripts/Client/Systems/CameraFollowSystem.cs, Assets/Scripts/Mixed/Commands/JoinGameRequest.cs, Assets/Scripts/Mixed/Commands/PlayerInput.cs, Assets/Scripts/Mixed/Components/KinematicCharacterControllerComponents.cs, Assets/Scripts/Mixed/Components/MaterialIdComponentData.cs, Assets/Scripts/Mixed/Components/PlayerIdComponentData.cs, Assets/Scripts/Mixed/Components/PlayerViewComponentData.cs, Assets/Scripts/Mixed/Components/PushForceComponentData.cs, Assets/Scripts/Mixed/Components/UpdateMaterialComponentData.cs, Assets/Scripts/Mixed/Systems/KinematicCharacterControllerSystems.cs, Assets/Scripts/Mixed/Systems/KinematicCharacterCotnrollerInput.cs, Assets/Scripts/Mixed/Systems/PlayerRotationSystem.cs, Assets/Scripts/Mixed/Systems/PushComponentSystem.cs, Assets/Scripts/Mixed/Utility/SelfFilteringClosestHitCollector.cs, Assets/Scripts/Server/Systems/HandleDisconnectSystem.cs, Assets/Scripts/Server/Systems/JoinGameServerSystem.cs
Removed unnecessary commands and using
No large code changes, just remove unused code and statements. Have ensured project still works with these changes by running around in sample scenes. 
Closes Issue #53
=> Refactored Systems to Remove WithBurst and Cleanup Input References

Assets/Scripts/Authoring/PlayerMovementAuthoringComponent.cs, Assets/Scripts/Client/Systems/CameraFollowSystem.cs, Assets/Scripts/Mixed/Commands/JoinGameRequest.cs, Assets/Scripts/Mixed/Commands/PlayerInput.cs, Assets/Scripts/Mixed/Components/KinematicCharacterControllerComponents.cs, Assets/Scripts/Mixed/Components/MaterialIdComponentData.cs, Assets/Scripts/Mixed/Components/PlayerIdComponentData.cs, Assets/Scripts/Mixed/Components/PlayerViewComponentData.cs, Assets/Scripts/Mixed/Components/PushForceComponentData.cs, Assets/Scripts/Mixed/Components/UpdateMaterialComponentData.cs, Assets/Scripts/Mixed/Systems/KinematicCharacterControllerSystems.cs, Assets/Scripts/Mixed/Systems/KinematicCharacterCotnrollerInput.cs, Assets/Scripts/Mixed/Systems/PlayerRotationSystem.cs, Assets/Scripts/Mixed/Systems/PushComponentSystem.cs, Assets/Scripts/Mixed/Utility/SelfFilteringClosestHitCollector.cs, Assets/Scripts/Server/Systems/HandleDisconnectSystem.cs, Assets/Scripts/Server/Systems/JoinGameServerSystem.cs
=> Refactored and cleaned existing systems

.config/dotnet-tools.json, .editorconfig, .githooks/post-commit, .githooks/post-merge, .githooks/pre-commit, .githooks/pre-push, .github/workflows/format.yml
=> Adding dot net format to project workflow.

.githooks/pre-commit, Assets/Scripts/GameMain.cs
Updated build patch and pre-commit hook for formatting.
Tested by executing the current command to ensure that it ignores correct folder.
=> Pre-Commit and formatting update

SampleImages/Demo/FollowGround.gif
=> Removed sample images directory

Contributing.md, Development.md
Included documentation for using dotnet format and ensuring it is installed in the project in development file. 
No changes to codebase
Closes #76
=> Dotnet Githooks Contributing Update

.githooks/pre-commit, .github/workflows/format.yml, Assets/Scripts/GameMain.cs
=> Adding filter for Formatting to only allow csharp files.

.githooks/pre-commit, .github/workflows/format.yml, Test Whitespace.md
=> Adding checks to avoid doing an empty formatting when no csharp files are edited.

Assets/Scripts/Client/Components/ConnectionComponentData.cs, Assets/Scripts/Client/Components/ConnectionComponentData.cs.meta, Assets/Scripts/Client/Systems/ConnectionSystem.cs, Assets/Scripts/Client/Systems/MenuManagerSystem.cs, Assets/Tests/PlayModeTests/NetworkTests/NetworkIntegrationTests.cs, Assets/Tests/PlayModeTests/Utility/WaitConnectionState.cs
Added in connection system to use singletons for connect and disconnect.
Tested connect and disconnect flow with current system along with the integration tests (manual and automatic).
Closes #85
=> Connection System Refactor

Assets/Scripts/Client/Systems/ConnectionSystem.cs, Assets/Scripts/UI/ConnectAction.cs, Assets/Scripts/UI/DisconnectAction.cs, Assets/Tests/EditModeTests/Client/ConnectionSystemTests.cs, Assets/Tests/PlayModeTests/NetworkTests/NetworkIntegrationTests.cs, ProjectSettings/ProjectSettings.asset
Hotfix for the bug introduced when disconnecting and reconnecting.
Testing by fixing various unit tests, playmode tests, and verifying the correct behavior using edit mode and playmode testing. 
The automated playmode tests are still broken but that is a future issue to resolve. 
=> Reconnect Clear Ghosts

Assets/Scripts/Mixed/Systems/PlayerRotationSystem.cs, Assets/Scripts/Server/Systems/JoinGameServerSystem.cs, Assets/Tests/EditModeTests/Server.meta, Assets/Tests/EditModeTests/Server/HandleDisconnectSystemTests.cs, Assets/Tests/EditModeTests/Server/HandleDisconnectSystemTests.cs.meta, Assets/Tests/EditModeTests/Server/JoinGameServerSystemTests.cs, Assets/Tests/EditModeTests/Server/JoinGameServerSystemTests.cs.meta
Added tests for the server systems in the game
Verified this test case by running the new edit mode tests and verifying 100% coverage of the PropHunt.Server.Systems namespace.
=> Server System Tests

Assets/Scripts/Mixed/Systems/KinematicCharacterControllerSystems.cs, Assets/Tests/EditModeTests/Mixed/KinematicChatacterControllerTests/KCCPushOverlappingTests.cs, Assets/Tests/EditModeTests/Mixed/KinematicChatacterControllerTests/KCCPushOverlappingTests.cs.meta
Adding tests for PushOverlappingSystem
=> Tests for the KCC Push Overlapping System

Assets/Scripts/Mixed/Systems/KinematicCharacterControllerSystems.cs, Assets/Tests/EditModeTests/Mixed/KinematicChatacterControllerTests/KCCMovementTests.cs, Assets/Tests/EditModeTests/Mixed/KinematicChatacterControllerTests/KCCMovementTests.cs.meta
Added tests for KCCMovementSystem
Closes #123
=> Added tests for KCCMovementSystem

Assets/Scripts/Mixed/Systems/KinematicCharacterControllerSystems.cs, Assets/Tests/EditModeTests/Mixed/KinematicChatacterControllerTests/KCCMoveWithGroundTests.cs, Assets/Tests/EditModeTests/Mixed/KinematicChatacterControllerTests/KCCMoveWithGroundTests.cs.meta
Created tests for the KCC Move with ground system
Closes #133 
Verified correctness of tests along with verifying coverage of the existing code. 
=> Tests for KCC Move With Ground System

Assets/Scripts/Client/Systems/ConnectionSystem.cs, Assets/Scripts/UI/ConnectAction.cs, Assets/Scripts/UI/UIManager.cs, Assets/Tests/EditModeTests/Client/CameraFollowSystemTests.cs, Assets/Tests/EditModeTests/Mixed.meta, Assets/Tests/EditModeTests/Mixed/KinematicChatacterControllerTests.meta, Assets/Tests/EditModeTests/UI.meta, Assets/Tests/EditModeTests/UI/MenuControllerTests.cs, Assets/Tests/EditModeTests/UI/MenuControllerTests.cs.meta, Assets/Tests/EditModeTests/UI/UIActionTests.cs, Assets/Tests/EditModeTests/UI/UIActionTests.cs.meta, Assets/Tests/EditModeTests/UI/UIManagerTests.cs, Assets/Tests/EditModeTests/UI/UIManagerTests.cs.meta
Added tests for the UI Scripts.
Closes #129 
=> UI Scripts Tests

.github/workflows/tests.yml
=> Switching to use Output variables instead of Env variables.

Assets/Scripts/Constants/KinematicCharacterControllerConstants.cs, Assets/Scripts/Constants/KinematicCharacterControllerConstants.cs.meta, Assets/Scripts/Mixed/Systems/KinematicCharacterControllerSystems.cs, Assets/Scripts/Mixed/Utility/KinematicCharacterControllerUtilities.cs, Assets/Tests/EditModeTests/Mixed/KCCUtilsTests.cs, Assets/Tests/EditModeTests/Mixed/KCCUtilsTests.cs.meta, Assets/Tests/EditModeTests/Mixed/KinematicChatacterControllerTests/KCCGroundedTests.cs, Assets/Tests/EditModeTests/Mixed/KinematicChatacterControllerTests/KCCPushOverlappingTests.cs, Assets/Tests/EditModeTests/Mixed/KinematicChatacterControllerTests/KCCSnapDownTests.cs, Assets/Tests/EditModeTests/Utils/PhysicsUtils.cs
=> KCC Utils Tests

Assets/Scripts/Mixed/GameObjects/SharedMaterials.cs, Assets/Tests/EditModeTests/EditModeTests.asmdef, Assets/Tests/EditModeTests/InputManagement.meta, Assets/Tests/EditModeTests/InputManagement/UnityServiceTests.cs, Assets/Tests/EditModeTests/InputManagement/UnityServiceTests.cs.meta, Assets/Tests/EditModeTests/Mixed/GameObjects.meta, Assets/Tests/EditModeTests/Mixed/GameObjects/SharedMaterialTests.cs, Assets/Tests/EditModeTests/Mixed/GameObjects/SharedMaterialTests.cs.meta, Assets/Tests/EditModeTests/Mixed/PredictionManagerTests.cs, Assets/Tests/EditModeTests/Mixed/PredictionManagerTests.cs.meta
Added tests for Shared materials, Unity Service, and Prediction States. 
Closes #143
=> Miscellaneous Tests

Contributing.md, pull_request_template.md
Added testing documentation
Closes #55
=> Mixed Testing Documentation

.github/workflows/tests.yml, Assets/Scripts/UI/UIManager.cs, Assets/Tests/EditModeTests/Mixed/GameObjects/SharedMaterialTests.cs
Improved test coverage reporting for github
=> Mixed Test Reporting

Assets/BuildConfigurations/ClientBaseBuildConfiguration.buildconfiguration, Assets/BuildConfigurations/ServerBaseBuildConfiguration.buildconfiguration, Assets/Prefabs/UI/MainMenuScreen.prefab, Assets/Scripts/Client/Systems/ConnectionSystem.cs, Assets/Scripts/GameMain.cs, Assets/Scripts/UI/ConnectAction.cs, Assets/Tests/EditModeTests/Client/ConnectionSystemTests.cs, Assets/Tests/EditModeTests/GameFlowTests.cs, Assets/Tests/EditModeTests/UI/UIActionTests.cs, Assets/Tests/PlayModeTests/NetworkTests/NetworkIntegrationTests.cs, Assets/Tests/PlayModeTests/PlayModeTests.asmdef
Updated the client server build to not launch a server on the client and vice versa 
Tested by creating new build and ensuring the client does not connect to the local instance. Also created and updated tests to verify changes.
=> Client Server Build Patch

Assets/Scenes/TestRoomScene.unity
Removing platforms for now
Tested by verifying removal of moving platforms
=> Removing moving platforms temporarily

Assets/BuildConfigurations/Win64-Client-Build.buildconfiguration, Assets/BuildConfigurations/Win64-Server-Build.buildconfiguration, Assets/Scenes/TestRoomScene.unity
Added back in moving platforms to verify the push overlapping system
Tested to ensure player is still pushed by moving platforms
=> Add Pushing Objects
